name: teststore
description: Another test
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  go_router: ^9.0.0
  shared_preferences: ^2.1.2
  dio: ^5.2.1+1
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  equatable: ^2.0.5
  google_fonts: ^4.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  retrofit_generator: ^7.0.6
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#5e914c"
  image: "assets/splash.png"
  android: true
  ios: true
  web: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/splash.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
